AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ClustersARN:
    Type: String
    Description: Cluster ARN
  ClustersSubnetIds:
    Description: Subnet IDs
    Type: "List<AWS::EC2::Subnet::Id>"

Resources:
  EKSTeastore:
    Type: 'AWS::EKS::Cluster'
    Properties:
      Name: teastore-cluster
      RoleArn: !Ref ClustersARN
      ResourcesVpcConfig:
        SubnetIds:
          !Ref ClustersSubnetIds
  EKSTeastoreNodegroup:
    Type: 'AWS::EKS::Nodegroup'
    Properties:
      AmiType: AL2_x86_64
      CapacityType: ON_DEMAND
      ClusterName: teastore-cluster
      InstanceTypes:
        - c4.xlarge
      NodegroupName: teastoreclusternodegroup
      NodeRole: !Ref ClustersARN
      Subnets:
        !Ref ClustersSubnetIds
    DependsOn: EKSTeastore
  EKSLoadTest:
    Type: 'AWS::EKS::Cluster'
    Properties:
      Name: teastore-loadtester
      RoleArn: !Ref ClustersARN
      ResourcesVpcConfig:
        SubnetIds:
          !Ref ClustersSubnetIds
  EKSLoadTestNodegroup:
    Type: 'AWS::EKS::Nodegroup'
    Properties:
      AmiType: AL2_x86_64
      CapacityType: ON_DEMAND
      ClusterName: teastore-loadtester
      InstanceTypes:
        - t3.medium
      NodegroupName: teastoreloadtesternodegroup
      NodeRole: !Ref ClustersARN
      Subnets:
        !Ref ClustersSubnetIds
    DependsOn: EKSLoadTest