AWSTemplateFormatVersion: 2010-09-09
Parameters:
  TeastoreInstanceType:
    Type: String
    Default: c4.xlarge
    Description: Default is c4.xlarge
  TeastoreInstances:
    Type: Number
    Default: "2"
    Description: Default is 2 instances. Cluster will always have this number of instances
  BackendInstanceType:
    Type: String
    Default: c4.xlarge
    Description: Default is c4.xlarge
  BackendInstances:
    Type: Number
    Default: "2"
    Description: Default is 2 instances. Cluster will always have this number of instances
  LocustInstances:
    Type: Number
    Default: "2"
    Description: Default is 2 instances. Cluster will always have this number of instances
  LocustInstanceType:
    Type: String
    Default: t3.medium
    Description: Default is t3.medium
  ClustersARN:
    Type: String
    Description: Cluster ARN
  ClustersSubnetIds:
    Description: Subnet IDs
    Type: "List<AWS::EC2::Subnet::Id>"

Resources:
  EKSTeastore:
    Type: "AWS::EKS::Cluster"
    Properties:
      Name: app-cluster
      RoleArn: !Ref ClustersARN
      ResourcesVpcConfig:
        SubnetIds: !Ref ClustersSubnetIds
  EKSTeastoreNodegroup:
    Type: "AWS::EKS::Nodegroup"
    Properties:
      AmiType: AL2_x86_64
      CapacityType: ON_DEMAND
      ClusterName: app-cluster
      ScalingConfig:
        MinSize: !Ref TeastoreInstances
        DesiredSize: !Ref TeastoreInstances
        MaxSize: !Ref TeastoreInstances
      InstanceTypes:
        - !Ref TeastoreInstanceType
      NodegroupName: teastoreclusternodegroup
      NodeRole: !Ref ClustersARN
      Subnets: !Ref ClustersSubnetIds
    DependsOn: EKSTeastore
  EKSLoadTest:
    Type: "AWS::EKS::Cluster"
    Properties:
      Name: loadtester-cluster
      RoleArn: !Ref ClustersARN
      ResourcesVpcConfig:
        SubnetIds: !Ref ClustersSubnetIds
  EKSLoadTestNodegroup:
    Type: "AWS::EKS::Nodegroup"
    Properties:
      AmiType: AL2_x86_64
      CapacityType: ON_DEMAND
      ClusterName: loadtester-cluster
      ScalingConfig:
        MinSize: !Ref LocustInstances
        DesiredSize: !Ref LocustInstances
        MaxSize: !Ref LocustInstances
      InstanceTypes:
        - !Ref LocustInstanceType
      NodegroupName: teastoreloadtesternodegroup
      NodeRole: !Ref ClustersARN
      Subnets: !Ref ClustersSubnetIds
    DependsOn: EKSLoadTest
  EKSBackend:
    Type: "AWS::EKS::Cluster"
    Properties:
      Name: backend-cluster
      RoleArn: !Ref ClustersARN
      ResourcesVpcConfig:
        SubnetIds: !Ref ClustersSubnetIds
  EKSBackendNodegroup:
    Type: "AWS::EKS::Nodegroup"
    Properties:
      AmiType: AL2_x86_64
      CapacityType: ON_DEMAND
      ClusterName: backend-cluster
      ScalingConfig:
        MinSize: !Ref BackendInstances
        DesiredSize: !Ref BackendInstances
        MaxSize: !Ref BackendInstances
      InstanceTypes:
        - !Ref BackendInstanceType
      NodegroupName: backendnodegroup
      NodeRole: !Ref ClustersARN
      Subnets: !Ref ClustersSubnetIds
    DependsOn: EKSBackend
  TeastoreWebUIPort:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      CidrIp: "0.0.0.0/0"
      Description: "Webui"
      FromPort: 30080
      GroupId: !GetAtt EKSTeastore.ClusterSecurityGroupId
      IpProtocol: tcp
      ToPort: 30080
  TeastoreZipkinPort:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      CidrIp: "0.0.0.0/0"
      Description: "Zipkin"
      FromPort: 32200
      GroupId: !GetAtt EKSBackend.ClusterSecurityGroupId
      IpProtocol: tcp
      ToPort: 32200
  TeastorePrometheusPort:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      CidrIp: "0.0.0.0/0"
      Description: "Prometheus"
      FromPort: 32201
      GroupId: !GetAtt EKSBackend.ClusterSecurityGroupId
      IpProtocol: tcp
      ToPort: 32201
  TeastorePrometheusBackendPort:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      CidrIp: "0.0.0.0/0"
      Description: "PrometheusBackend"
      FromPort: 32205
      GroupId: !GetAtt EKSBackend.ClusterSecurityGroupId
      IpProtocol: tcp
      ToPort: 32205
  TeastoreLokiPort:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      CidrIp: "0.0.0.0/0"
      Description: "Loki"
      FromPort: 32202
      GroupId: !GetAtt EKSBackend.ClusterSecurityGroupId
      IpProtocol: tcp
      ToPort: 32202
  TeastoreGrafanaPort:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      CidrIp: "0.0.0.0/0"
      Description: "Grafana"
      FromPort: 32203
      GroupId: !GetAtt EKSBackend.ClusterSecurityGroupId
      IpProtocol: tcp
      ToPort: 32203
  TeastoreJaegerPort:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      CidrIp: "0.0.0.0/0"
      Description: "Jaeger"
      FromPort: 32204
      GroupId: !GetAtt EKSBackend.ClusterSecurityGroupId
      IpProtocol: tcp
      ToPort: 32204
  TeastoreJaegerBackendPort:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      CidrIp: "0.0.0.0/0"
      Description: "JaegerBackend"
      FromPort: 32206
      GroupId: !GetAtt EKSBackend.ClusterSecurityGroupId
      IpProtocol: tcp
      ToPort: 32206
  TeastoreLocustPort:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      CidrIp: "0.0.0.0/0"
      Description: "Locust"
      FromPort: 32001
      GroupId: !GetAtt EKSLoadTest.ClusterSecurityGroupId
      IpProtocol: tcp
      ToPort: 32001
