apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert --volumes hostPath -f docker-compose_default.yaml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: jaeger
  name: jaeger
  namespace: default
spec:
  type: NodePort
  ports:
    - name: "webui"
      port: 16686
      targetPort: 16686
      nodePort: 32204
    - name: "collector"
      port: 14250
      targetPort: 14250
    - name: "collectora"
      port: 14268
      targetPort: 14268
    - name: "collectorb"
      port: 4317
      targetPort: 4317
  
  selector:
    io.kompose.service: jaeger
status:
  loadBalancer: {}
