apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert --volumes hostPath -f docker-compose_default.yaml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: jaeger
  name: jaeger
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jaeger
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert --volumes hostPath -f docker-compose_default.yaml
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/k8s-default: "true"
        io.kompose.service: jaeger
    spec:
      containers:
        - image: jaegertracing/all-in-one:latest
          name: jaeger
          resources:
            requests:
              memory: "2Gi"
            limits:
              memory: "2Gi"
          env:
          - name: COLLECTOR_OTLP_ENABLED
            value: "true"
          - name: SPAN_STORAGE_TYPE
            value: "badger"
          - name: BADGER_EPHEMERAL
            value: "false"
          - name: BADGER_DIRECTORY_VALUE
            value: "/tmp/badger/data"
          - name: BADGER_DIRECTORY_KEY
            value: "/tmp/badger/key"
          - name: SAMPLING_STRATEGIES-FILE
            value: "/sampling-config.json"
          volumeMounts:
            - name: config-volume
              mountPath: /sampling-config.json
              subPath: config.json
          ports:
            - containerPort: 16686
              protocol: TCP
            - containerPort: 14268
              protocol: TCP
            - containerPort: 14250
              protocol: TCP
            - containerPort: 4317
              protocol: TCP
      volumes:
        - name: config-volume
          configMap:
            name: jaeger-sampling-config
      restartPolicy: Always
status: {}
