apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  config.yaml: |
    receivers:
      kubeletstats:
        collection_interval: 60s
        auth_type: "serviceAccount"
        endpoint: "${env:K8S_NODE_NAME}:10250"
        insecure_skip_verify: true

      hostmetrics:
        root_path: /hostfs
        collection_interval: 60s
        scrapers:
          load:
          disk:
          filesystem:
          memory:
          network:
          paging:
    
      mysql:
        endpoint: teastore-db:3306
        username: root
        password: rootpassword
        database: teadb
        collection_interval: 60s
    
      otlp:
        protocols:
          grpc:
          http:
    
      filelog:
        include:
        - /var/log/pods/*/*/*.log
        exclude:
        - /var/log/pods/*/otel-collector/*.log
        start_at: beginning
        include_file_path: true
        include_file_name: false    
    
    processors:
      filter:
        metrics:
          exclude:
            match_type: strict
            metric_names:
              - queueSize
    
      attributes:
        actions:
          - action: insert
            key: log_file_name
            from_attribute: log.file.name
          - action: insert
            key: loki.attribute.labels
            value: log_file_name
    
    exporters:
      logging:
        verbosity: normal
    
      loki:
        endpoint: http://loki:3100/loki/api/v1/push

      prometheus:
        endpoint: "0.0.0.0:8889"

      otlp:
        endpoint: "jaeger:4317"
        tls:
          insecure: true
    
    service:
      pipelines:
        metrics:
          receivers: [otlp, mysql, kubeletstats, hostmetrics]
          exporters: [prometheus]
        traces:
          receivers: [otlp]
          exporters: [otlp]                        
        logs:
          receivers: [otlp, filelog]
          processors: [attributes]
          exporters: [logging, loki]
