apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  config.yaml: |
    receivers:
      hostmetrics:
        root_path: /hostfs
        collection_interval: 5s
        scrapers:
          load:
          memory:
    
      otlp:
        protocols:
          grpc:
          http:
    
      filelog:
        include:
        - /var/log/pods/*/*/*.log
        exclude:
        - /var/log/pods/*/otel-collector/*.log
        start_at: beginning
        include_file_path: true
        include_file_name: false    
    
    processors:
      filter:
        metrics:
          exclude:
            match_type: strict
            metric_names:
              - queueSize
    
      attributes:
        actions:
          - action: insert
            key: log_file_name
            from_attribute: log.file.name
          - action: insert
            key: loki.attribute.labels
            value: log_file_name
    
    exporters:
      logging:
        verbosity: normal
    
      loki:
        endpoint: http://loki:3100/loki/api/v1/push

      prometheus:
        endpoint: "0.0.0.0:8889"

      otlp:
        endpoint: "jaeger:4317"
        tls:
          insecure: true
    
    service:
      pipelines:
        metrics:
          receivers: [hostmetrics]
          exporters: [prometheus]
        traces:
          receivers: [otlp]
          exporters: [otlp]                        
        logs:
          receivers: [otlp, filelog]
          processors: [attributes]
          exporters: [logging, loki]
