apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  config.yaml: |
    receivers:
      hostmetrics:
        root_path: /hostfs
        collection_interval: 5s
        scrapers:
          load:
          disk:
          filesystem:
          memory:
          network:
          paging:
    
      mysql:
        endpoint: db:3306
        username: root
        password: root
        database: teadb
        collection_interval: 10s
    
      otlp:
        protocols:
          grpc:
          http:
    
      filelog:
        include: [/var/log/*.log]
    
    processors:
      filter:
        metrics:
          exclude:
            match_type: strict
            metric_names:
              - queueSize
    
      attributes:
        actions:
          - action: insert
            key: log_file_name
            from_attribute: log.file.name
          - action: insert
            key: loki.attribute.labels
            value: log_file_name
    
    exporters:
      logging:
        verbosity: detailed
    
      zipkin:
        endpoint: http://zipkin:9411/api/v2/spans
    
      jaeger:
        endpoint: jaeger:14250
        tls:
          insecure: true
    
      loki:
        endpoint: http://loki:3100/loki/api/v1/push
    
      prometheus:
        endpoint: "0.0.0.0:8889"
    
    service:
      pipelines:
        metrics:
          receivers: [mysql]
          exporters: [logging]
        traces:
          receivers: [otlp]
          exporters: [zipkin, jaeger]
        logs:
          receivers: [otlp, filelog]
          processors: [attributes]
          exporters: [loki]