apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert --volumes hostPath -f docker-compose_default.yaml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: zipkin
  name: zipkin
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zipkin
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert --volumes hostPath -f docker-compose_default.yaml
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/k8s-default: "true"
        io.kompose.service: zipkin
    spec:
      containers:
        - image: openzipkin/zipkin:latest
          name: zipkin
          ports:
            - containerPort: 9411
              hostPort: 9411
              protocol: TCP
          resources: 
            requests:
              cpu: 100m
      restartPolicy: Always
status: {}
