---
apiVersion: v1
kind: Service
metadata:
  name: teastore-db-service
spec:
  type: ClusterIP
  selector:
    app: "teastore-db"
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-db
  labels:
    app: teastore-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teastore-db
  template:
    metadata:
      labels:
        app: teastore-db
    spec:
      containers:
        - name: teastore-db-container
          image: ghcr.io/viniciusbrg/teastore-monolithic-otel/teastore-db:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306