---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-app
  labels:
    app: teastore-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: teastore-app
  template:
    metadata:
      labels:
        app: teastore-app
    spec:
      containers:
        - name: teastore-app-container
          image: ghcr.io/viniciusbrg/teastore-monolithic-otel/teastore-webui:latest
          env:
            - name: HOST_NAME
              value: "webui"
            - name: REGISTRY_HOST
              value: "registry"
            - name: DB_HOST
              value: $(TEASTORE_DB_SERVICE_SERVICE_HOST)
            - name: DB_PORT
              value: "3306"
            - name: OTEL_SERVICE_NAME
              value: "teastore-app"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://collector:4317"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"

          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-service
spec:
  type: NodePort
  selector:
    app: teastore-app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
