apiVersion: batch/v1
kind: Job
metadata:
  labels:
    role: locust-master
    app: locust-master
  name: locust-master
spec:
  completions: 1
  parallelism: 1
  completionMode: Indexed  # required for the feature
  template:
    metadata:
      labels:
        role: locust-master
        app: locust-master
    spec:
      containers:
        - image: locustio/locust
          imagePullPolicy: Always
          name: master
          args: ["--master", "--headless", "--expect-workers=2", "--csv=/tmp/results", "--host=http://3.238.93.131:30080/tools.descartes.teastore.webui"]
          volumeMounts:
            - mountPath: /home/locust
              name: locust-scripts
          ports:
            - containerPort: 5557
              name: comm
            - containerPort: 5558
              name: comm-plus-1
            - containerPort: 8089
              name: web-ui
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: locust-scripts
          configMap:
            name: scripts-cm