apiVersion: batch/v1
kind: Job
metadata:
  labels:
    role: locust-worker
    app: locust-worker
  name: locust-worker
spec:
  completions: 2
  parallelism: 2
  completionMode: Indexed  # required for the feature
  template:
    metadata:
      labels:
        role: locust-worker
        app: locust-worker
    spec:
      containers:
        - image: locustio/locust
          imagePullPolicy: Always
          name: worker
          args: ["--worker", "--master-host=locust-master"]
          volumeMounts:
            - mountPath: /home/locust
              name: locust-scripts
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: locust-scripts
          configMap:
            name: scripts-cm