apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert --volumes hostPath -f docker-compose_default.yaml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: zipkin
  name: zipkin
  namespace: default
spec:
  type: NodePort
  ports:
    - name: "9411"
      port: 9411
      targetPort: 9411
      nodePort: 32200
  selector:
    io.kompose.service: zipkin
status:
  loadBalancer: {}
